# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 08:33


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wish",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("wish", models.TextField(verbose_name="Zde napi\u0161te, co si p\u0159ejete.")),
                ("multiple_reservation", models.BooleanField(default=False, verbose_name="Lze rezervovat v\xedcekr\xe1t")),
                ("reserved_count", models.PositiveIntegerField(default=0)),
                ("secret", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, verbose_name="Kdo jste?")),
                ("slug", models.CharField(max_length=8, unique=True)),
                ("edit_slug", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="wish",
            name="wishlist",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wishes", to="wishlist.WishList"),
        ),
    ]
