# Generated by Django 4.2.7 on 2023-11-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wish",
            name="wish",
            field=models.TextField(verbose_name="Zde napiš, co si přeješ."),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Kdo jsi?"),
        ),
    ]
