# Generated by Django 4.2.7 on 2025-11-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0002_alter_wish_wish_alter_wishlist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Popis seznamu (nepovinné)"),
        ),
    ]
