repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements

-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort

-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.9

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.7.0]
